spring:
  profiles:
    active: @profiles.active@
  cache:
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: classpath:ehcache.xml
alm:
  exchangeRateMode: "3"  ## 1: 严格，2：宽松，3：配置文件
logging:
  level:
    com.gykj.patch: @logging.level@
    org.springframework: info
    org.apache.ibatis: info
  config: classpath:logback-plus.xml


